---
- name : This is first play
  hosts: localhost
  gather_facts: false
  tasks:
  # - name: Here we are using Ansible Ping module to check the current hosts list in host group serverlist
  #   ping:
  # - name: Here we are using Ansible Ping module to check the current hosts list in host group serverlist
  #   debug:  
  #     var: ansible_facts
  # - name: List local directory
  #   ansible.builtin.shell:
  #       cmd: ls -l
  #   register: lsout
   
  # - debug:
  #     msg: "{{lsout.stdout_lines}}" 

  # - name: List filesystems 
  #   ansible.builtin.shell:
  #       cmd: df  
  #   register: dfout
   
  # - debug:
  #     msg: "{{dfout.stdout_lines}}" 


  # - name: List local file system 
  #   ansible.builtin.shell:
  #       chdir: ~/.ssh
  #       cmd: ls -l  
  #   register: lfout
   
  # - debug:
  #     msg: "{{lfout.stdout_lines}}"        

  - name: Here we are using Ansible add_host module to add a host to in-memory inventory
    ansible.builtin.add_host:
      name: servera
      ansible_host: '52.118.145.13'
      ansible_user: root
      groups: serverlist
      foobar: 42
  # - name: Here we are using Ansible Ping module to check the current hosts list in host group serverlist
    # ping:
    


- name: Example playbook to showcase hostvars
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Display the specific hostvars that are set in the inventory for each host
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]



# - name: Look up A (IPv4) records for example.org
#   hosts: localhost
#   gather_facts: false
#   tasks:
#     - debug:
#         msg: "{{ query('community.dns.lookup', 'servera') }}"


- name: List servers
  hosts: serverlist
  gather_facts: True
  tasks:
    - name: Again using Ansible Ping module to check the current hosts list in host group serverlist after using Ansible add_host module
      ping:
    - name: check facts 
      debug:
        var: ansible_facts  

    - name: List remote directory
      ansible.builtin.shell:
          cmd: ls -l
      register: lsout
    
    - debug:
        msg: "{{lsout.stdout_lines}}" 


    - name: List remote filesystems 
      ansible.builtin.shell:
          cmd: df  
      register: dfout
    
    - debug:
        msg: "{{dfout.stdout_lines}}" 

    - name: List remote filesystems 
      ansible.builtin.shell:
        chdir: "/tmp/tfws-368831675"
        cmd: ls -l  
        register: lfout

    - debug:
        msg: "{lfout.stdout_lines}}" 

  # - name: Wait for the VSI to be SSH-able
  #   wait_for_connection:
  #   