---
- name : This is first play
  hosts: localhost
  gather_facts: false
  tasks:
  # - name: Here we are using Ansible Ping module to check the current hosts list in host group serverlist
  #   ping:
  - name: Here we are using Ansible Ping module to check the current hosts list in host group serverlist
    debug:  
      var: ansible_facts

  - name: Here we are using Ansible add_host module to add a host to in-memory inventory
    ansible.builtin.add_host:
      name: servera
      ansible_host: '52.118.145.13'
      ansible_user: root
      groups: serverlist
      foobar: 42
  # - name: Here we are using Ansible Ping module to check the current hosts list in host group serverlist
    # ping:
    
- name: List servers
  hosts: serverlist
  gather_facts: True
  tasks:
    - name: Again using Ansible Ping module to check the current hosts list in host group serverlist after using Ansible add_host module
      ping:
    - name: check facts 
      debug:
        var: ansible_facts  


    # - name: Wait for the VSI to be SSH-able
    #   wait_for_connection:
    #   